### PR TITLE
DHCP / PHY reset support

### LINKED ISSUE #8: Update handling of DHCP lease loss
Update the means of handling a DHCP lease loss (or IP address update).

In these cases, our IP has changed from under us. If this occurs, we need to close all open sockets and do not allow them to be used.

### LINKED ISSUE #9: Failed connect() calls will leak sockets
If `connect()` fails, sockets handles will be dropped until there are no more available.

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR updates the network stack to have a `reset()` function that can be called to shut down all active sockets and a means of allowing DHCP to close all active sockets if the IP address changes

This should make applications robust against changing IP addresses and/or ethernet plug cycling.

This fixes #8 

This also fixes #9 by updating the error handler to close the socket (which returns the handle for usage).

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -97,6 +98,13 @@ where
                     if let Some(cidr) = config.address {
                         if cidr.address().is_unicast() {
                             interface.update_ip_addrs(|addrs| {
+                                // If our address has updated or is not specified, close all
+                                // sockets.
+                                if cidr.address().is_unspecified() || addrs[0] == IpCidr::Ipv4(cidr)
+                                {
+                                    self.close_sockets();
+                                }
```
Comment (irwineffect) [inline src/lib.rs:106]: If we're checking if the address was updated, don't we want to use 
```rust 
addrs[0] != IpCidr::Ipv4(cidr)
```

File: src/lib.rs [hunk 2]
```diff
@@ -123,6 +131,27 @@ where
...
+        }
+    }
+
+    /// Handle a disconnection of the physical interface.
+    pub fn handle_link_reset(&mut self) {
+        // Reset the DHCP client.
+        if let Some(ref mut client) = *self.dhcp_client.borrow_mut() {
+            client.reset(smoltcp::time::Instant::from_millis(-1));
+        }
+    }
```
Comment (irwineffect) [inline src/lib.rs:153]: Should we reset the interface address to `0.0.0.0` at the same time here?
https://docs.rs/smoltcp/0.7.0/smoltcp/dhcp/struct.Dhcpv4Client.html#method.reset

File: src/lib.rs (hunk 1 above)
Comment (ryan-summers) [reply src/lib.rs]: Good catch. I'm unsure why this wasn't causing me troubles previously.

File: src/lib.rs (hunk 2 above)
Comment (ryan-summers) [reply src/lib.rs]: Reset added - this was intentional at the time, but the more I think about it, the more I'm changing how I'm thinking about it.

**Review by irwineffect — APPROVED** [review]
